# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Portfolio of Léo"
weight = 1

[fr]
languageName = "Français"
languagedirection = "ltr"
title = "Portfolio de Léo"
weight = 2